version: "3.8"

services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
      - ./nginx/html/:/usr/share/nginx/html

  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/fluentd.conf:/fluentd/etc/fluentd.conf:ro
      - ./nginx/log:/var/log/nginx
    ports:
      - 28000:28000
    environment:
      FLUENTD_CONF: fluentd.conf
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.8.0
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
    driver: local
